Added synthetic data for observation of Device Generated Data
department-of-veterans-affairs/health-apis-patient-generated-data pull request #10
Opened 2020-11-17 15:51 UTC by that-guy-is-it

2020-11-17 18:06 UTC, apeirats-va commented
Need to update liquibase and Populaterator to get these added to the db. Let me know if you need help with that.

2020-11-17 19:01 UTC, jblefkove-va commented
My initial thought for observation was that we would mine the mapping spreadsheets for the other PGD API for sample values. (For Questionnaire/QuestionnaireResponse we couldn't really do that.)

That said, I didn't realize the FHIR spec had samples for device-generated observations specifically. This looks sufficient for our needs.

2020-11-17 21:26 UTC, apeirats-va commented on patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
> +  }
Call this method in `populate(...)`

Also run `local-db.sh` and verify it populates without errors.

2020-11-17 21:30 UTC, apeirats-va commented on patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
> +  }
P.S. it fails validation on ekg.json

2020-11-18 14:43 UTC, jblefkove-va requested changes

2020-11-18 14:43 UTC, jblefkove-va commented on patient-generated-data/src/main/resources/db/changelog/db.changelog-master.yaml
> +  - changeSet:
keep a newline between changesets

2020-11-18 14:43 UTC, jblefkove-va commented on patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
> +        statement.setObject(2, new ObjectMapper().writeValueAsString(observation));
There is a shared `MAPPER` field that can be used here instead of a new mapper. (Update the other resources as well.)

2020-11-18 14:43 UTC, jblefkove-va commented on patient-generated-data-synthetic/src/test/resources/observation/ekg.json
> +}
Add a newline at end-of-file here, and for the other json file. (You can see GitHub noting it in the diff).

2020-11-18 14:43 UTC, jblefkove-va commented on patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
> -
restore these removed newlines

2020-11-18 14:43 UTC, jblefkove-va commented on patient-generated-data-synthetic/src/test/java/gov/va/api/health/patientgenerateddata/Populaterator.java
> +    observation(connection);
Since there needs to be some arbitrary order for the resources... how about alphabetical?

2020-11-18 14:50 UTC, jblefkove-va commented
As a general rule for each PR, do a full rebuild on the command-line, and commit any files that were reformatted.

2020-11-18 16:41 UTC, jblefkove-va approved these changes

2020-11-18 16:42 UTC, merged